### ISSUE TITLE
Default filenames like `foo.bar.lua` will not autorun

### ISSUE THREAD

**Issue by Qxcl** [novacbn/gmodproj#14]
Garry's Mod seems to not want to autorun a script with a name containing two dots. I have changed my `.gmodprojmanifest` so the first dot is now a dash in the generated filenames, and it autoruns as expected.

**Comment by novacbn** [comment]
Tried to replicate on a Windows client listen server, and Windows srcds instance with the default addon template. Autoran just fine, gonna install Garry's Mod and srcds on my Linux laptop to test later.

Might be something with Garry's Mod Linux/macOS support.

**Comment by Qxcl** [comment]
Yes, this happens on my Linux dedicated server. I really should have mentioned that. 

Thanks for looking into this. :+1:

**Comment by novacbn** [comment]
Was able to reproduce the issue, so changed the default behavior.
