### ISSUE TITLE
Add macOS builds

### ISSUE THREAD

**Issue by novacbn** [novacbn/gmodproj#7]
Requested by #6

**Comment by novacbn** [comment]
Currently working on this in [novacbn/gmodproj-dev](https://github.com/novacbn/gmodproj-dev) since it's easier to manage with TravisCI that way.

Also don't have a macOS device myself, so doing troubleshooting via TravisCI build process.

**Comment by novacbn** [comment]
https://github.com/novacbn/gmodproj-dev/releases/tag/latest

**Comment by Qxcl** [comment]
Thanks for the quick response. I've installed the dev binary for macOS and it's working great so far. 

❤️

**Comment by novacbn** [comment]
No problem! Glad it's working for you.
